FROM debian:stretch
RUN apt-get update 
RUN apt-get install -y sudo
ADD . /src
WORKDIR /src
RUN cd /src && ./install.sh && make tests

RUN apt-get install -y devscripts
RUN debuild -i -us -uc -b

CMD ["/bin/bash"]