#!/bin/sh

# Contributed by Steven Penny, https://github.com/nu8
# Cosmetical changes and minor fixes by Ilya Sher

file_name=$1
var_name=$(tr /. __ <<eof
$file_name
eof
)
len=$(wc -c < "$file_name")
data=$(od -A n -t d1 -v "$file_name" | sed 's/[- ]\+/,/g;1s/,//')
printf '// Generated by %s from input file %s
unsigned char %s[] = {
%s
};
unsigned int %s_len = %s;
' "$0" "$file_name" "$var_name" "$data" "$var_name" "$len"
