name: Build
on:
  - push
  - pull_request_target

jobs:
  build-internal-apt:
    timeout-minutes: 5
    name: ${{ matrix.container }} - ${{ matrix.compiler.cc }}-${{ matrix.compiler.version }}
    runs-on: ${{ matrix.container }}
    strategy:
      matrix:
        container: [ "ubuntu-24.04" ]
        compiler:
          - {version: 12, package: g++, cc: gcc, cxx: g++}
          - {version: 13, package: g++, cc: gcc, cxx: g++}
          - {version: 14, package: g++, cc: gcc, cxx: g++}
          - {version: 16, package: clang, cc: clang, cxx: clang++}
          - {version: 17, package: clang, cc: clang, cxx: clang++}
          - {version: 18, package: clang, cc: clang, cxx: clang++}
    steps:
      - uses: actions/checkout@v5
      - name: Setup Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y man ${{ matrix.compiler.package }}-${{ matrix.compiler.version }}
      - name: Install and Test
        env:
          CC: ${{ matrix.compiler.cc }}-${{ matrix.compiler.version }}
          CXX: ${{ matrix.compiler.cxx }}-${{ matrix.compiler.version }}
        run: (./install.sh && make tests test-installation)

  build-external-apt:
    timeout-minutes: 5
    name: ${{ matrix.container }} - ${{ matrix.compiler.cc }}-${{ matrix.compiler.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [ "debian:12" ] # https://hub.docker.com/_/debian/
        compiler:
          - { version: 11, package: g++, cc: gcc, cxx: g++ }
          - { version: 12, package: g++, cc: gcc, cxx: g++ }
          - { version: 13, package: clang, cc: clang, cxx: clang++ }
          - { version: 14, package: clang, cc: clang, cxx: clang++ }
          - { version: 15, package: clang, cc: clang, cxx: clang++ }
          - { version: 16, package: clang, cc: clang, cxx: clang++ }
    container:
      image: ${{ matrix.container }}
      options: --user root
    steps:
      - uses: actions/checkout@v5
      - name: Setup Compiler
        run: |
          apt-get update
          apt-get install -y man ${{ matrix.compiler.package }}-${{ matrix.compiler.version }} uuid-runtime
      - name: Install and Test
        env:
          CC: ${{ matrix.compiler.cc }}-${{ matrix.compiler.version }}
          CXX: ${{ matrix.compiler.cxx }}-${{ matrix.compiler.version }}
        run: (./install.sh && make tests test-installation)

  build-external-pacman:
    timeout-minutes: 5
    name: ${{ matrix.container }} - ${{ matrix.compiler.cc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [ "archlinux:latest" ] # https://hub.docker.com/_/archlinux/
        compiler:
          - {package: gcc, cc: gcc, cxx: g++}
          - {package: clang, cc: clang, cxx: clang++}
    container:
      image: ${{ matrix.container }}
      options: --user root
    steps:
      - uses: actions/checkout@v5
      - name: Setup Compiler
        run: |
          pacman -Syu --noconfirm
          pacman -Sy --noconfirm man-db wget curl ${{ matrix.compiler.package }}
      - name: Install and Test
        env:
          CC: ${{ matrix.compiler.cc }}
          CXX: ${{ matrix.compiler.cxx }}
        run: (./install.sh && make tests test-installation)

  build-external-yum:
    timeout-minutes: 10
    name: ${{ matrix.container }} - ${{ matrix.compiler.cc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [ "fedora:latest"  ] # "amazonlinux:2023" is broken because of missing pandoc # https://hub.docker.com/_/fedora/
        compiler:
          - { package: gcc-c++, cc: gcc, cxx: g++ }
          - { package: clang, cc: clang, cxx: clang++ }
    container:
      image: ${{ matrix.container }}
      options: --user root
    steps:
      - uses: actions/checkout@v5
      - name: Install AmazonLinux deps needed specifically for GitHub action
        if: startsWith(matrix.container, 'amazonlinux')
        run: yum -y install tar xz gzip
      - name: Setup Compiler
        run: |
          dnf5 install 'dnf5-command(groupinstall)'
          yum -y install man ${{ matrix.compiler.package }}
      - name: Install and Test
        env:
          CC: ${{ matrix.compiler.cc }}
          CXX: ${{ matrix.compiler.cxx }}
        run: (./install.sh && make tests test-installation)

  build-mac:
    timeout-minutes: 10
    name: ${{ matrix.container }} - ${{ matrix.compiler.cc }}-${{ matrix.compiler.version }}
    runs-on: ${{ matrix.container }}
    strategy:
      matrix:
        container: [ "macos-latest" ]
        compiler:
          - { version: 14, package: gcc, cc: gcc, cxx: g++ }
          - { version: 15, package: gcc, cc: gcc, cxx: g++ }
          - { version: latest, package: clang, cc: clang, cxx: clang++ }
    steps:
      - uses: actions/checkout@v5
      - name: Setup Dependencies
        run: brew install cmake ninja
      - name: Setup gcc
        if: startsWith(matrix.compiler.package, 'gcc')
        run: |
          brew install ${{ matrix.compiler.package }}@${{ matrix.compiler.version }}
          echo "CC=${{ matrix.compiler.cc }}-${{ matrix.compiler.version }}" >> $GITHUB_ENV
          echo "CXX=${{ matrix.compiler.cxx }}-${{ matrix.compiler.version }}" >> $GITHUB_ENV
      - name: Setup clang
        if: startsWith(matrix.compiler.package, 'clang')
        run: |
          echo "CC=${{ matrix.compiler.cc }}" >> $GITHUB_ENV
          echo "CXX=${{ matrix.compiler.cxx }}" >> $GITHUB_ENV
      - name: Install and Test
        run: (./install.sh && make tests test-installation)

  build-other-arch-gcc:
    timeout-minutes: 15
    name: ${{ matrix.container }} [${{ matrix.arch }}] - gcc
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [ "bookworm" ] # Has GCC 12
        arch: [ "aarch64", "s390x", "ppc64le" ]   # , "armv6", "armv7" -- 32 bits archs, currently not supported by ngs
    steps:
      - uses: actions/checkout@v5
      - uses: uraimo/run-on-arch-action@v3
        name: Run commands
        id: runcmd
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.container }}
          # Not required, but speeds up builds by storing container images in GitHub package registry.
          githubToken: ${{ github.token }}
          # Mount the local folder as /ngs in the container
          dockerRunArgs: |
            --volume "${PWD}:/ngs"
          install: |
            apt-get update
            apt-get install -y man sudo uuid-runtime

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            cd /ngs && ./install.sh && make tests test-installation
            uname -a
